# Generated by Django 4.2.5 on 2023-12-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbltwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=50)),
                ('pname', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('wsiteverified', models.CharField(default='', max_length=50)),
                ('projprog', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
