# Generated by Django 4.2.5 on 2023-12-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tbltwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='', max_length=50)),
                ('end', models.CharField(default='', max_length=50)),
                ('dwnldpages', models.IntegerField()),
                ('checkpages', models.IntegerField()),
            ],
        ),
    ]
