# Generated by Django 4.2.5 on 2023-12-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tblthree'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblone',
            table='res_tblone_master',
        ),
    ]
