# Generated by Django 4.2.5 on 2023-12-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tblone_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblone',
            table=None,
        ),
    ]
